# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-22 07:47
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('shade', models.CharField(blank=True, max_length=50, null=True)),
                ('date_obtained', models.DateField(default=datetime.date.today, verbose_name='Date Obtained')),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('unit', models.CharField(blank=True, choices=[('g', 'g'), ('mL', 'mL'), ('oz', 'oz')], max_length=2, null=True)),
                ('rating', models.IntegerField(choices=[(5, 'A+'), (4.7, 'A'), (4.3, 'A-'), (4, 'B+'), (3.7, 'B'), (3.3, 'B-'), (3, 'C'), (2, 'D'), (1, 'F')])),
                ('notes', models.TextField(blank=True, null=True)),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.Brand')),
            ],
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('base', 'Base'), ('eyes', 'Eyes'), ('brow', 'Brows'), ('lip', 'Lips'), ('chk', 'Cheeks'), ('sc', 'Skincare'), ('tool', 'Tools'), ('etc', 'Other')], default='base', max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='use',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.Type'),
        ),
    ]
